export const ADD = 'add'
export const DELETE = 'delete'
export const FIND = 'find'
export const NEXT = 'next'
export const PRIOR = 'prior'
export const INITSTEP = 'initStep'
export const CHANGE_POS = 'change_pos'
export const CLEAR_FROM = 'clear_from'

export const KEY = 'passport'
export const SET_STORAGE = 'setStorage'
export const REMOVE_STORAGE = 'removeStorage'
